### ISSUE TITLE
[CHECKLIST] Tangle AVS Implementation

### ISSUE THREAD

**Issue by Tjemmmic** [tangle-network/avs#3]
## Overview
The Tangle AVS is a blueprint that is able to run either a Tangle validator or operator node.

An Eigenlayer operator should be able to participate in Tangle using the precompile interface we have for Tangle operators. We want to use a bridge to dispatch these messages through. When we receive messages on Tangle, we expect to process it as normal in the precompile on Tangle.

For example, we handle Eigenlayer registration as dispatching a message to setup a validator on Tangle. We could have the ability to register as a validator, an operator, or both. Each would have a unique flow and its own message to dispatch.

### Tasks
- [x] #26
- [x] #25
- [x] #24
#### AVS Steps and Requirements
- Registers for EigenLayer and AVS
- AVS runs Tangle Node in Validator mode and exposes the session keys and account key
- We bridge the registration to some arbitrary contract on Tangle
- That contract has TNT which is given to that address
- AVS listens for it's balance/transfers regularly, checking its TNT balance. When it's non-zero it submits all the validator registration extrinsics.
- The AVS's validator should be in the waiting set at this point.

### Steps to [Getting on the Testnet](https://docs.eigenlayer.xyz/eigenlayer/avs-guides/how-to-build-an-avs)
- [x] [[TASK] Trust Modeling](https://github.com/tangle-network/eigensdk-rs/issues/12)
- [x] [[TASK] Operator and End User Instructions](https://github.com/tangle-network/eigensdk-rs/issues/13)
- [x] [[TASK] Communication Channels for AVS Upgrades](https://github.com/tangle-network/eigensdk-rs/issues/14)
- [x] [[TASK] Node Specifications](https://github.com/tangle-network/eigensdk-rs/issues/16)
- [x] [[TASK] Deployment](https://github.com/tangle-network/eigensdk-rs/issues/17)

### Onboarding/Registration Flow
![image](https://github.com/user-attachments/assets/9bfcf390-19c6-45ca-9316-45c84105df62)

### Offboarding/Deregistration Flow
![image](https://github.com/user-attachments/assets/13a60818-f1d0-4a4d-9b72-5ecb8900ff9f)
